### PR TITLE
Fix docs

### LINKED ISSUE #14: Fix interface doc markdown
- br is not working
- tables are not complete (while it works if I try to open the same file with markdown preview)

image

### PR DESCRIPTION
**Pull request by szabo137**
Closes #14 

## Checklist

- [x] Tests are passing
- [x] Docs were updated and workflow is passing

### CODE REVIEW

**Comment by grasph** [comment]
I'm not convinced by the new interface name (neither by the package name btw). 

However, I prefer to postpone discussions on naming, once we have agreed on the interface definition and on the scope of this package. It's easier to name something, once we know what the thing is. So it's fine for me to keep the new wording for time being.

+1

**Review by grasph — APPROVED** [review]

**Comment by Moelf** [comment]
I suggest we don't say anything about "object with LV inside" other than this package just focus on LV and "particle" or whatever particle shouldn't be `<:AbstractLorentzVector`

File: docs/make.jl [hunk 1]
```diff
@@ -1,27 +1,34 @@
...
 DocMeta.setdocmeta!(
   LorentzVectorBase, :DocTestSetup, :(using LorentzVectorBase); recursive=true
 )
 
-const numbered_pages = [
-  file for file in readdir(joinpath(@__DIR__, "src")) if
-  file != "index.md" && splitext(file)[2] == ".md"
+pages = [
+  "Home" => "index.md", "Interface" => "10-interface.md", "Reference" => "95-reference.md"
 ]
```
Comment (mmikhasenko) [inline docs/make.jl:17]: I'd vote for automatic discovery of pages, but there is nothing wrong updating list manualy

File: docs/make.jl [hunk 2]
```diff
@@ -1,27 +1,34 @@
...
 makedocs(;
   modules=[LorentzVectorBase],
   authors="Uwe Hernandez Acosta <u.hernandez@hzdr.de>",
-  repo="https://github.com/JuliaHEP/LorentzVectorBase.jl/blob/{commit}{path}#{line}",
+  repo=Documenter.Remotes.GitHub("JuliaHEP", "LorentzVectorBase.jl"),
   sitename="LorentzVectorBase.jl",
   format=Documenter.HTML(;
+    prettyurls=get(ENV, "CI", "false") == "true",
     canonical="https://JuliaHEP.github.io/LorentzVectorBase.jl",
-    repolink="https://github.com/JuliaHEP/LorentzVectorBase.jl",
```
Comment (mmikhasenko) [inline docs/make.jl:20]: IIRC,
`repolink` is needed to get to repository when clicking to GitLab, and I think the Documenter complains when it is not specified

**Comment by mmikhasenko** [comment]
minor comments, can be merged once resolved.
Thanks

File: docs/make.jl (hunk 1 above)
Comment (szabo137) [reply docs/make.jl:17]: Since we don't have that many pages, I would like to go for more control. Furthermore, it seems like something is broken with this in the current implementation, e.g. the local build does not link the pages correctly.

**Comment by szabo137** [comment]
I removed the docs preview todo for now but opened #23
